#!/usr/bin/env python3

@app_views.route('/status', methods=['GET'])
def status():
    """
    This function handles the /api/v1/status route.
    It returns a status message with the "OK" status.

    Returns:
        JSON response with the status message.
    """
    return jsonify({"status": "OK"})
